export AZURE_TENANT_ID=
export AZURE_SUBSCRIPTION_ID=

export AZURE_MGMT_CLIENT_ID=
export AZURE_MGMT_CLIENT_SECRET=

export AZURE_KEY_VAULT_CLIENT_ID=
export AZURE_KEY_VAULT_CLIENT_SECRET=
export AZURE_KEY_VAULT_CLIENT_OBJECT_ID=

export AZURE_KEY_VAULT_NAME=
export AZURE_KEY_VAULT_URL=

export AZURE_STORAGE_NAME=
export AZURE_STORAGE_KEY=
export AZURE_STORAGE_FILES=
